### ISSUE TITLE
Add checks

### ISSUE THREAD

**Issue by Hype3808** [RPSMain/fanta#32]
### Summary

Add code checks to the repo

### What is the feature request for?

Core

### The Problem

Just adding checks.

### The Ideal Solution

Add it. idk how

**Comment by RPSMain** [comment]
ddev reference?

**Comment by Hype3808** [comment]
idk... like CodeQL thingi idk... u could copy those checks from pycord lol

**Comment by RPSMain** [comment]
Done with github apps.
